-- Migration 0008: Drop obsolete 5-arg overload of run_cumulative_impact
-- Created: 2026-09-08
--
-- Background:
--   Migrations 0003/0004 created run_cumulative_impact with 5 args
--   (_project_id, _activity_ids, _profile_name, _description, _user).
--   db/functions/run_cumulative_impact.sql later added a 6th argument
--   (_floor NUMERIC DEFAULT 0.001) for the cost-floor rescaling. Because
--   CREATE OR REPLACE only replaces an identical signature, the 6-arg
--   version was created as a *new* overload alongside the old 5-arg one.
--
--   Any 5-arg call is then ambiguous -- the 6th arg has a DEFAULT, so both
--   candidates match -- and Postgres raises:
--     function bioprotect.run_cumulative_impact(integer, integer[],
--     unknown, unknown, unknown) is not unique
--   This hit cost-profile generation via activity_handler and any call to
--   run_impact_pipeline, which invokes run_cumulative_impact with 5 args.
--
-- Fix: drop the old 5-arg signature; keep only the 6-arg one.
-- Same class of bug as migration 0006.

DROP FUNCTION IF EXISTS bioprotect.run_cumulative_impact(integer, integer[], text, text, text);
